[project]
name = "accusleepy"
version = "0.1.0"
description = ""
authors = [
    {name = "Zeke Barger",email = "zekebarger@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
    "numpy (>=2.2.4,<3.0.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "torch (>=2.6.0,<3.0.0)",
    "torchvision (>=0.21.0,<0.22.0)",
    "scipy (>=1.15.2,<2.0.0)",
    "pyside6 (>=6.8.3,<7.0.0)",
    "matplotlib (>=3.10.1,<4.0.0)",
    "joblib (>=1.4.2,<2.0.0)",
    "pillow (>=11.1.0,<12.0.0)",
    "fastparquet (>=2024.11.0,<2025.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
